#!/usr/bin/env python3
"""prepare_jus.py — generate ndsrecomp bank configs for Jump Ultimate Stars.

Track C bridge: converts the dsd (ds-decomp) extraction + symbol metadata
into TOML configs consumed by `nds_recompile` (tools/ndsrecomp, cloned).

Inputs (all confirmed — see decomp/docs/MEMORY_MAP.md):
  rom/jus.nds                     ROM (SHA-1 for game.toml)
  extract/arm9/arm9.bin           656832 B @ 0x02000000, entry 0x02000800 (uncompressed)
  extract/arm9/itcm.bin            31552 B @ 0x01FF8000
  extract/arm9/dtcm.bin             4160 B @ 0x027C0000
  extract/arm7/arm7.bin           165552 B @ 0x02380000, entry 0x02380000
  decomp/arm9/symbols.txt         dsd function symbols (name, mode, size, addr)
  decomp/arm9/itcm/symbols.txt
  decomp/arm9/dtcm/symbols.txt

Outputs (all regenerable; commit-friendly):
  recomp/config/jus_arm9_main.toml
  recomp/config/jus_arm9_itcm.toml
  recomp/config/jus_arm9_dtcm.toml
  recomp/config/jus_arm7_main.toml
  recomp/game.toml                 runner config ([game].sha1 etc.)

Overlays are deliberately NOT banked here: they are runtime-copied (relocated)
code and run on the runner's Tier-3 interpreter floor first; native coverage
comes later via content-validated RAM-bank captures (SM64DS WS-A2 model).
ARM7 has no dsd symbols yet -> single seed entry, discovery mode.

Usage: py tools/scripts/prepare_jus.py
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EXTRACT = ROOT / "extract"
DECOMP = ROOT / "decomp"
RECOMP = ROOT / "recomp"
ROM = ROOT / "rom" / "jus.nds"

SYM_RE = re.compile(
    r"^(?P<name>\S+)\s+kind:function\((?P<mode>arm|thumb),"
    r"size=(?P<size>0x[0-9a-fA-F]+)\)\s+addr:(?P<addr>0x[0-9a-fA-F]+)\s*$"
)


def sha1_of(path: Path) -> str:
    h = hashlib.sha1()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def sanitize(name: str, seen: set[str]) -> str:
    s = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if not s or not re.match(r"^[A-Za-z_]", s):
        s = "f_" + s
    base, i = s, 2
    while s in seen:
        s = f"{base}_{i}"
        i += 1
    seen.add(s)
    return s


def load_functions(symbols_path: Path) -> list[dict]:
    """Parse dsd symbols.txt -> [{'addr','mode','size','name'}] (functions only)."""
    funcs: list[dict] = []
    seen_names: set[str] = set()
    seen_addrs: set[int] = set()
    for raw in symbols_path.read_text(encoding="utf-8").splitlines():
        m = SYM_RE.match(raw.strip())
        if not m:
            continue
        addr = int(m.group("addr"), 16)
        if addr in seen_addrs:
            continue
        seen_addrs.add(addr)
        funcs.append({
            "addr": addr,
            "mode": m.group("mode"),
            "size": int(m.group("size"), 16),
            "name": sanitize(m.group("name"), seen_names),
        })
    funcs.sort(key=lambda f: f["addr"])
    return funcs


def size_is_valid(mode: str, size: int) -> bool:
    align = 2 if mode == "thumb" else 4
    return size >= align and size % align == 0


def emit_bank_toml(
    out_path: Path,
    *,
    title: str,
    prog_id: str,
    cpu: str,
    isa: str,
    load: int,
    entry: int,
    bin_path: Path,
    funcs: list[dict],
    authoritative: bool,
) -> None:
    bin_size = bin_path.stat().st_size
    image_end = load + bin_size
    dropped_sizes = 0
    in_image = []
    for f in funcs:
        if not (load <= f["addr"] < image_end):
            continue
        if not size_is_valid(f["mode"], f["size"]):
            f = dict(f, size=0)  # omit size; kills authoritative below
            dropped_sizes += 1
        in_image.append(f)
    if dropped_sizes or not in_image:
        authoritative = False

    lines = [
        f"# {out_path.name} — generated by tools/scripts/prepare_jus.py. Do not hand-edit.",
        f"# Source binary: {bin_path.relative_to(ROOT).as_posix()}",
        "",
        "[program]",
        f'name = "{title}"',
        f'id = "{prog_id}"',
        f'cpu = "{cpu}"',
        f'isa = "{isa}"',
        f"load_address = 0x{load:08X}",
        f"size = 0x{bin_size:X}",
        f"entry_pc = 0x{entry:08X}",
        f"authoritative_entry_points = {str(authoritative).lower()}",
        "",
        "[identity]",
        f'sha1 = "{sha1_of(bin_path)}"',
        "",
    ]
    for f in in_image:
        lines.append("[[entry_point]]")
        lines.append(f"addr = 0x{f['addr']:08X}")
        if f["size"]:
            lines.append(f"size = 0x{f['size']:X}")
        lines.append(f'mode = "{f["mode"]}"')
        lines.append(f'name = "{f["name"]}"')
        lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(
        f"  {out_path.relative_to(ROOT).as_posix()}: {len(in_image)} entries "
        f"(authoritative={str(authoritative).lower()}, "
        f"dropped_sizes={dropped_sizes}, image=0x{load:08X}..0x{image_end:08X})"
    )


def emit_game_toml(out_path: Path, rom_sha1: str) -> None:
    lines = [
        f"# {out_path.name} — generated by tools/scripts/prepare_jus.py. Do not hand-edit.",
        "# Runner config — see tools/ndsrecomp/README.md 'Interactive display configuration'.",
        "",
        "[game]",
        f'sha1 = "{rom_sha1}"',
        "",
        "[display]",
        'screen_layout = "stacked"',
        'adaptive_widescreen = "none"',
        "",
        "[system]",
        'startup_mode = "automatic"',
        "",
        "[cartridge]",
        "# Owner's cartridge dump: 65536-byte .sav. The 64 KiB backup chip is an",
        "# EEPROM (GBATEK classes flash at 256 KiB+): the game reprograms bytes in",
        "# place without erase (full byte store, 0->1 allowed). The runner's flash",
        "# model AND-programs (1->0 only), which silently corrupted re-saves and made",
        "# the game's read-back verify fail with the restart-console error after a",
        "# deck edit (see decomp/docs/SAVEBUG-SESSION3.md).",
        'save_type = "eeprom"',
        "save_size = 65536",
        "",
        "# Generic pad-button -> touchscreen-tap shortcuts (title-agnostic; no Prime",
        "# Controls gate). Each entry synthesizes a stylus tap at (x, y) when the",
        "# bound pad button is pressed. Use case: JUS's in-game L/R assist binding",
        "# only covers 2 support koma; spare arcade-stick buttons can each summon a",
        "# 3rd/4th support panel. Calibrate x/y to YOUR deck's on-screen support",
        "# icons (DS touchscreen pixels: x=0..255, y=0..191). tap_frames /",
        "# release_frames are optional (default 2 each).",
        "#",
        "# [[controls.taps]]",
        "# button = \"Pad LB\"      # Pad A/B/X/Y, LB/RB, LT/RT, L3/R3, D-pad, Start/Back",
        "# x = 40",
        "# y = 150",
        "# tap_frames = 2",
        "# release_frames = 2",
        "#",
        "# [[controls.taps]]",
        "# button = \"Pad RB\"",
        "# x = 210",
        "# y = 150",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"  {out_path.relative_to(ROOT).as_posix()}: [game].sha1 = {rom_sha1}")


def main() -> int:
    print("prepare_jus.py — JUS -> ndsrecomp config generation")
    required = [
        ROM,
        EXTRACT / "arm9" / "arm9.bin",
        EXTRACT / "arm9" / "itcm.bin",
        EXTRACT / "arm9" / "dtcm.bin",
        EXTRACT / "arm7" / "arm7.bin",
        DECOMP / "arm9" / "symbols.txt",
        DECOMP / "arm9" / "itcm" / "symbols.txt",
        DECOMP / "arm9" / "dtcm" / "symbols.txt",
    ]
    missing = [p for p in required if not p.is_file()]
    if missing:
        for p in missing:
            print(f"MISSING: {p.relative_to(ROOT).as_posix()}", file=sys.stderr)
        return 1

    print(" banks:")
    cfg = RECOMP / "config"

    arm9_funcs = load_functions(DECOMP / "arm9" / "symbols.txt")
    emit_bank_toml(
        cfg / "jus_arm9_main.toml",
        title="JUS ARM9 main", prog_id="jus_arm9_main",
        cpu="arm9", isa="armv5te",
        load=0x02000000, entry=0x02000800,
        bin_path=EXTRACT / "arm9" / "arm9.bin",
        funcs=arm9_funcs, authoritative=True,
    )

    itcm_funcs = load_functions(DECOMP / "arm9" / "itcm" / "symbols.txt")
    emit_bank_toml(
        cfg / "jus_arm9_itcm.toml",
        title="JUS ITCM", prog_id="jus_arm9_itcm",
        cpu="arm9", isa="armv5te",
        load=0x01FF8000, entry=0x01FF8000,
        bin_path=EXTRACT / "arm9" / "itcm.bin",
        funcs=itcm_funcs, authoritative=True,
    )

    dtcm_funcs = load_functions(DECOMP / "arm9" / "dtcm" / "symbols.txt")
    emit_bank_toml(
        cfg / "jus_arm9_dtcm.toml",
        title="JUS DTCM", prog_id="jus_arm9_dtcm",
        cpu="arm9", isa="armv5te",
        load=0x027C0000, entry=0x027C0000,
        bin_path=EXTRACT / "arm9" / "dtcm.bin",
        funcs=dtcm_funcs, authoritative=True,
    )

    # ARM7: no dsd symbols yet — seed with the header entry only; the
    # function finder discovers the boot closure (SM64DS model).
    emit_bank_toml(
        cfg / "jus_arm7_main.toml",
        title="JUS ARM7", prog_id="jus_arm7_main",
        cpu="arm7", isa="armv4t",
        load=0x02380000, entry=0x02380000,
        bin_path=EXTRACT / "arm7" / "arm7.bin",
        funcs=[{"addr": 0x02380000, "mode": "arm", "size": 0, "name": "_start"}],
        authoritative=False,
    )

    print(" runner:")
    emit_game_toml(RECOMP / "game.toml", sha1_of(ROM))

    print(
        "\nNext (bank generation):\n"
        "  tools/ndsrecomp/recompiler/build/nds_recompile.exe "
        "--config recomp/config/jus_arm9_main.toml --bin extract/arm9/arm9.bin "
        "--out recomp/generated --bank jus_arm9_main\n"
        "  (repeat for jus_arm9_itcm / itcm.bin, jus_arm9_dtcm / dtcm.bin, "
        "jus_arm7_main / arm7.bin)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
