"""build.py — materialize the english-translation payloads from the user's own
patched English ROM (rom/jus-en.nds).

The committed recipe is `recomp/eng_diff.json`, generated by
`tools/scripts/eng_diff.py`: the verified list of NitroFS files whose CONTENT
differs between the stock Japanese ROM and the patched English ROM (arm9,
arm7, overlays and banner are identical and are intentionally NOT shipped).
For each changed file the English bytes are pulled from the English ROM's own
FNT/FAT and written under files/ (NitroFS mirror) for the overlay resolver.

Nothing under files/ is committed: it is rebuilt locally from ROMs you own.
"""
from __future__ import annotations

import json
import sys

DIFF_MANIFEST = "recomp/eng_diff.json"


def build(ctx):
    en_rom = ctx.rom.parent / "jus-en.nds"
    if not en_rom.is_file():
        raise SystemExit(
            "[!] english-translation: rom/jus-en.nds not found.\n"
            "    Copy your patched English ROM to rom/jus-en.nds (never\n"
            "    committed to git) and re-run "
            "'py tools/scripts/mods_manage.py build english-translation'.")

    manifest = ctx.repo / DIFF_MANIFEST
    if not manifest.is_file():
        print(f"  {DIFF_MANIFEST} missing — regenerating via eng_diff.py")
        ctx.run(["py", str(ctx.scripts / "eng_diff.py"),
                 "--english", str(en_rom)])
    rep = json.loads(manifest.read_text(encoding="utf-8"))
    changed = rep["files"]["changed"]
    if not changed:
        raise SystemExit("[!] english-translation: diff manifest lists no "
                         "changed files — check eng_diff.json")

    if str(ctx.scripts) not in sys.path:
        sys.path.insert(0, str(ctx.scripts))
    import eng_diff as ed  # noqa: E402

    en = ed.NdsRom(en_rom)
    for r in changed:
        path = r["path"]
        if path not in en.fnt:
            raise SystemExit(f"[!] {path}: missing from English ROM FNT")
        data = en.read_fid(en.fnt[path])
        if len(data) != r["size"]["english"]:
            raise SystemExit(
                f"[!] {path}: English ROM size drift vs manifest "
                f"({len(data)} != {r['size']['english']}) — regenerate "
                f"eng_diff.json")
        out = ctx.files / path
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(data)
        print(f"  {path}: {r['size']['stock']} -> {len(data)} bytes")
    print(f"  wrote {len(changed)} payload file(s) from {en_rom.name}")
